
scalar DateTime
scalar Json

# type BSCPositionWithShares {
#   id: Int!
#   goblin: String!
#   owner: String!
#   debtShare: String!
#   isActive: Boolean!
#   updatedAt: DateTime
# }

type BSCEvent {
  logIndex: Int!
  transactionHash: String!
  transactionIndex: Int!
  address: String!
  blockNumber: Int!
  event: String!
  returnValues: Json
  contextValues: Json
  positionId: Int
  timestamp: Int
  updatedAt: DateTime!
}

type Query {
  # bscPositionById(positionId: Int!): BSCPositionWithShares
  bscEventByTransactionIndex(from: Int!, to: Int!, types: [String!]!): [BSCEvent]
}

# type Mutation {}
